name: ecommerce_web_admin_panel
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter


  # Utility Packages
  intl: ^0.19.0
  lottie: ^3.1.2
  connectivity_plus: ^6.0.5
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.0
  flutter_typeahead: ^5.2.0
  flutter_dropzone: ^4.0.3
  multi_select_flutter: ^4.1.3
  clipboard: ^0.1.3

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  
  # Web Specific
  web: ^0.5.1
  http: ^1.1.2
  html: ^0.15.4
  fl_chart: ^0.66.2
  data_table_2: ^2.5.9
  url_strategy: ^0.2.0

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/on_boarding_images/
    - assets/images/animated_images/
    - assets/images/category_icons/
    - assets/images/carousel_images/
    - assets/images/products/
    - assets/images/user/
    - assets/icons/payment_methods/
    - assets/logos/
